yatube/about/urls.py
from django.urls import path

from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'


urlpatterns = [
    path('group/<slug:slug>/', views.GroupPostsView.as_view(),
         name='group_list'),
    path('profile/<str:username>/', views.ProfileView.as_view(),
         name='profile'),
    path('posts/<int:pk>/', views.PostDetailView.as_view(),
         name='post_detail'),
    path('create/', views.PostCreateView.as_view(),
         name='post_create'),
    path('posts/<int:pk>/edit/', views.PostEditView.as_view(),
         name='post_edit'),
    path('posts/<int:pk>/comment/', views.AddCommentView.as_view(),
         name='add_comment'),
    path('follow/', views.FollowingListView.as_view(),
         name='follow_index'),
    path('profile/<str:username>/follow/', views.FollowAuthor.as_view(),
         name='profile_follow'),
    path('profile/<str:username>/unfollow/', views.UnFollowAuthor.as_view(),
         name='profile_unfollow'),
    path('', (views.Index.as_view()),
         name='index_page'),
]

yatube/users/urls.py
from django.contrib.auth.views import (
    LogoutView,
    LoginView,
    PasswordChangeView,
    PasswordResetView,
    PasswordChangeDoneView,
    PasswordResetConfirmView,
    PasswordResetDoneView,
    PasswordResetCompleteView
)
from django.urls import path

from . import views


app_name = 'users'

urlpatterns = [
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path(
        'password_reset/',
        PasswordResetView.as_view(
            template_name='users/password_reset_form.html'),
        name='password_reset_form'
    ),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'),
        name='password_reset_done'
    ),
    path(
        'password_reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html'),
        name='password_reset_confirm'
    ),
    path(
        'reset/done/',
        PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'),
        name='password_reset_complete'
    ),
    path(
        'password_change/',
        PasswordChangeView.as_view(
            template_name='users/password_change_form.html'),
        name='password_change'
    ),
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html'),
        name='password_change_done'
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.permission_denied'
handler500 = 'core.views.server_error'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('', include('posts.urls', namespace='posts')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import models

from core.models import CreatedModel
User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200, verbose_name='Название группы')
    slug = models.SlugField(max_length=50, unique=True, verbose_name='Адрес')
    description = models.TextField(verbose_name='Описание группы')

    class Meta:
        verbose_name = 'сообщество'
        verbose_name_plural = 'сообщества'

    def __str__(self):
        return self.title


class Post(CreatedModel):
    text = models.TextField(
        verbose_name='Текст поста',
        help_text='Текст поста',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор',
        help_text='Автор поста',
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        related_name='posts',
        on_delete=models.SET_NULL,
        verbose_name='Группа',
        help_text='Группа поста',
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True,
        help_text='Картинка для поста',
    )

    class Meta:
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'
        ordering = ('-pub_date',)

    def __str__(self):
        return self.text[:settings.POST_TITLE_SHOW_LENGTH]


class Comment(CreatedModel):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
    )
    text = models.TextField(
        verbose_name='Комментарии к посту',
        help_text='Введите комментарий',
    )

    class Meta:
        ordering = ('-pub_date',)

    def __str__(self):
        return self.text


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        related_name='follower',
        on_delete=models.CASCADE,
    )
    author = models.ForeignKey(
        User,
        related_name='following',
        on_delete=models.CASCADE,
    )

yatube/posts/forms.py
from django import forms
from django.contrib.auth import get_user_model

from .models import Comment, Post


User = get_user_model()


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('group', 'text', 'image')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, ListView, UpdateView
from django.views.generic.base import View
from django.views.generic.detail import DetailView
from django.views.generic.edit import FormMixin

from .models import Group, Follow, Post, User, Comment

from .forms import CommentForm, PostForm


class Index(ListView):
    paginate_by = settings.COUNT_OF_POSTS_PAGINATOR
    model = Post
    template_name = 'posts/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['index'] = True
        context['cache_seconds'] = settings.CACHE_PAGE_SECONDS
        return context

    def get_queryset(self):
        return Post.objects.select_related('author', 'group')


class GroupPostsView(ListView):
    paginate_by = settings.COUNT_OF_POSTS_PAGINATOR
    model = Post
    template_name = 'posts/group_list.html'

    def get_group_instance(self):
        return get_object_or_404(Group, slug=self.kwargs.get('slug'))

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        group = self.get_group_instance()
        context['group'] = group
        return context

    def get_queryset(self):
        return (Post.objects.select_related('author')
                .filter(group__slug=self.kwargs.get('slug')))


class ProfileView(ListView):
    paginate_by = settings.COUNT_OF_POSTS_PAGINATOR
    model = Post
    template_name = 'posts/profile.html'

    def get_queryset(self):
        return (Post.objects.select_related('group')
                .filter(author__username=self.kwargs.get('username')))

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        author = get_object_or_404(User, username=self.kwargs.get('username'))
        context['author'] = author
        context['following'] = (
            self.request.user.is_authenticated
            and author.following.filter(user=self.request.user).exists()
        )
        return context


class PostDetailView(DetailView, FormMixin):
    model = Post
    template_name = 'posts/post_detail.html'
    form_class = CommentForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        post = get_object_or_404(Post, pk=self.object.pk)
        comments = post.comments.all()
        context['comments'] = comments
        return context

    def get_queryset(self):
        return (Post.objects.select_related('author').all()
                .select_related('group').all())


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    form_class = PostForm
    template_name = 'posts/create_post.html'

    def form_valid(self, form):
        new_post = form.save(commit=False)
        new_post.author = self.request.user
        new_post.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy(
            'posts:profile',
            args=(self.request.user.username,)
        )


class PostEditView(LoginRequiredMixin, UpdateView):
    model = Post
    form_class = PostForm
    template_name = 'posts/create_post.html'
    object = None

    def get_context_data(self):
        context = super().get_context_data()
        context['is_edit'] = True
        return context

    def get_queryset(self):
        return (Post.objects.select_related('group').all()
                .select_related('author').all())

    def dispatch(self, request, *args, **kwargs):
        instance = self.get_object()
        if instance.author != self.request.user:
            return redirect(
                reverse_lazy('posts:post_detail', args=(instance.pk,))
            )
        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return reverse_lazy('posts:post_detail', args=(self.object.pk,))


class AddCommentView(LoginRequiredMixin, CreateView):
    model = Comment
    form_class = CommentForm

    def form_valid(self, form):
        post = get_object_or_404(Post, pk=self.kwargs.get('pk'))
        new_comment = form.save(commit=False)
        new_comment.post = post
        new_comment.author = self.request.user
        new_comment.save()
        return redirect(reverse('posts:post_detail', args=(post.pk,)))


class FollowingListView(LoginRequiredMixin, ListView):
    paginate_by = settings.COUNT_OF_POSTS_PAGINATOR
    model = Post
    template_name = 'posts/index.html'

    def get_context_data(self):
        context = super().get_context_data()
        context['following_view'] = True
        context['cache_seconds'] = settings.CACHE_PAGE_SECONDS
        return context

    def get_queryset(self):
        return Post.objects.filter(author__following__user=self.request.user)


class FollowAuthor(LoginRequiredMixin, View):
    model = User
    template_name = 'posts/profile.html'

    def get(self, *args, **kwargs):
        author = get_object_or_404(User, username=self.kwargs.get('username'))
        if author != self.request.user:
            Follow.objects.get_or_create(author=author, user=self.request.user)
        return redirect(reverse(
            'posts:profile',
            args=(self.kwargs.get('username'),)
        ))


class UnFollowAuthor(LoginRequiredMixin, View):
    model = User
    template_name = 'posts/profile.html'

    def get(self, *args, **kwargs):
        author = get_object_or_404(User, username=self.kwargs.get('username'))
        is_follower = Follow.objects.filter(
            user=self.request.user,
            author=author,
        )
        is_follower.delete()
        return redirect(
            reverse('posts:profile', args=(self.kwargs.get('username'),))
        )

yatube/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>    
</footer>

yatube/templates/includes/form.html
{% load user_filters %}
<div class="card-body">
  {% if form.errors %}
    {% for field in form %}
      {% for error in field.errors %}
        <div class="alert alert-danger">{{ error|escape }}</div>{% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
      <div class="alert alert-danger">{{ error|escape }}</div>{% endfor %}
  {% endif %}
  <form method="post"
    {% if action_url %} action="{% url action_url %}" {% endif %}
        enctype="multipart/form-data">
    {% csrf_token %}
    {% for field in form %}
      <div class="form-group row my-3 p-3"
        {% if field.field.required %} aria-required="true" {% else %}
           aria-required="false" {% endif %}>
        <label for="{{ field.id_for_label }}">
          {{ field.label }}
          {% if field.field.required %}
            <span class="required text-danger">*</span>{% endif %}
        </label>
        <div>
          {{ field|addclass:'form-control' }}
          {% if field.help_text %}
            <small id="{{ field.id_for_label }}-help"
                   class="form-text text-muted">{{ field.help_text|safe }}</small>
          {% endif %}
        </div>
      </div>
    {% endfor %}
    <div class="col-md-6 offset-md-4">
      <button type="submit" class="btn btn-primary">
        {{ button_name|default:"кнопка" }}</button>
      {% if forgot_password %}
        <a href="{% url 'users:password_reset_form' %}" class="btn btn-link">Забыли
          пароль?</a>
      {% endif %}
    </div>
  </form>
</div>

yatube/templates/includes/header.html
{% load static %}
{% with request.resolver_match.view_name as view_name %}
  <nav class="navbar navbar-light navbar-expand-lg fixed-top" style="background-color: lightskyblue">
    <div class="container justify-content-between col-md-auto">
      <a class="navbar-brand" href="{% url 'posts:index_page' %}">
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="" />
        <span style="color:red">Ya</span>tube
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-end" id="navbarScroll">
        <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
          <li class="nav-item"> 
            <a class="nav-link {% if view_name == 'about:author' %}active{% endif %}"
                href="{% url 'about:author' %}">Об авторе</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if view_name == 'about:tech' %}active{% endif %}" 
              href="{% url 'about:tech' %}">Технологии</a>
          </li>
          {% if user.is_authenticated %}
            <li class="nav-item"> 
              <a class="nav-link {% if view_name == 'posts:post_create' %}active{% endif %}"
                href={% url "posts:post_create" %}>Новая запись</a>
            </li>
            <li class="nav-item"> 
              <a class="nav-link link-light {% if view_name == 'users:password_change' %}active{% endif %}"
                href={% url "users:password_change" %}>Изменить пароль</a>
            </li>
            <li class="nav-item"> 
              <a class="nav-link link-light {% if view_name == 'users:logout' %}active{% endif %}"
                href={% url "users:logout" %}>Выйти</a>
            </li>
            <li> 
              Пользователь: {{ user.username }}
            </li>
          {% else %}
            <li class="nav-item"> 
              <a class="nav-link link-light {% if view_name == 'users:login' %}active{% endif %}"
                href="{% url 'users:login' %}">Войти</a>
            </li>
            <li class="nav-item"> 
              <a class="nav-link link-light {% if view_name == 'users:signup' %}active{% endif %}" 
                href="{% url 'users:signup' %}">Регистрация</a>
            </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>
{% endwith %}

yatube/templates/includes/post.html
<article class="col-12">
  {% load thumbnail %}
  <ul>
    <li>Дата публикации: {{ post.pub_date|date:"d E Y" }}</li>
    {% if is_detail %}
      <li>
        Автор: {{ post.author.get_full_name }}
        <br/>
        <a href="{% url 'posts:profile' post.author.username %}">Все посты
          автора</a>
      </li>
    {% endif %}
  </ul>
  {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img my-auto" src="{{ im.url }}" alt="картинка к посту">
  {% endthumbnail %}
  <p>{{ post.text }}</p>
  <p>
    <a href="{% url 'posts:post_detail' post.id %}">подробная информация</a>
    {% if link_to_group %}
      <br/>
      Все записи группы:<a
      href="{% url 'posts:group_list' post.group.slug %}">{{ post.group.slug }}</a>
    {% endif %}
  </p>
</article>
{% if not forloop.last %}
  <hr/>
{% endif %}