yatube/about/urls.py
from django.urls import path

from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'


urlpatterns = [
    path('group/<slug:slug>/', views.GroupPostsView.as_view(),
         name='group_list'),
    path('profile/<str:username>/', views.ProfileView.as_view(),
         name='profile'),
    path('posts/<int:pk>/', views.PostDetailView.as_view(),
         name='post_detail'),
    path('create/', views.PostCreateView.as_view(),
         name='post_create'),
    path('posts/<int:pk>/edit/', views.PostEditView.as_view(),
         name='post_edit'),
    path('posts/<int:pk>/comment/', views.AddCommentView.as_view(),
         name='add_comment'),
    path('follow/', views.FollowingListView.as_view(),
         name='follow_index'),
    path('profile/<str:username>/follow/', views.FollowAuthor.as_view(),
         name='profile_follow'),
    path('profile/<str:username>/unfollow/', views.UnFollowAuthor.as_view(),
         name='profile_unfollow'),
    path('', (views.Index.as_view()),
         name='index_page'),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.permission_denied'
handler500 = 'core.views.server_error'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('', include('posts.urls', namespace='posts')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import models

from core.models import CreatedModel
User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200, verbose_name='Название группы')
    slug = models.SlugField(max_length=50, unique=True, verbose_name='Адрес')
    description = models.TextField(verbose_name='Описание группы')

    class Meta:
        verbose_name = 'сообщество'
        verbose_name_plural = 'сообщества'

    def __str__(self):
        return self.title


class Post(CreatedModel):
    text = models.TextField(
        verbose_name='Текст поста',
        help_text='Текст поста',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор',
        help_text='Автор поста',
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        related_name='posts',
        on_delete=models.SET_NULL,
        verbose_name='Группа',
        help_text='Группа поста',
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True,
        help_text='Картинка для поста',
    )

    class Meta:
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'
        ordering = ('-pub_date',)

    def __str__(self):
        return self.text[:settings.POST_TITLE_SHOW_LENGTH]


class Comment(CreatedModel):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
    )
    text = models.TextField(
        verbose_name='Комментарии к посту',
        help_text='Введите комментарий',
    )

    class Meta:
        ordering = ('-pub_date',)

    def __str__(self):
        return self.text


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        related_name='follower',
        on_delete=models.CASCADE,
    )
    author = models.ForeignKey(
        User,
        related_name='following',
        on_delete=models.CASCADE,
    )

yatube/posts/forms.py
from django import forms
from django.contrib.auth import get_user_model

from .models import Comment, Post


User = get_user_model()


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('group', 'text', 'image')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, ListView, UpdateView
from django.views.generic.base import View
from django.views.generic.detail import DetailView
from django.views.generic.edit import FormMixin

from .models import Group, Follow, Post, User, Comment

from .forms import CommentForm, PostForm


class Index(ListView):
    paginate_by = settings.COUNT_OF_POSTS_PAGINATOR
    model = Post
    template_name = 'posts/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['index'] = True
        context['cache_seconds'] = settings.CACHE_PAGE_SECONDS
        return context

    def get_queryset(self):
        return Post.objects.select_related('author', 'group')


class GroupPostsView(ListView):
    paginate_by = settings.COUNT_OF_POSTS_PAGINATOR
    model = Post
    template_name = 'posts/group_list.html'

    def get_group_instance(self):
        return get_object_or_404(Group, slug=self.kwargs.get('slug'))

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        group = self.get_group_instance()
        context['group'] = group
        return context

    def get_queryset(self):
        return (Post.objects.select_related('author')
                .filter(group__slug=self.kwargs.get('slug')))


class ProfileView(ListView):
    paginate_by = settings.COUNT_OF_POSTS_PAGINATOR
    model = Post
    template_name = 'posts/profile.html'

    def get_queryset(self):
        return (Post.objects.select_related('group')
                .filter(author__username=self.kwargs.get('username')))

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        author = get_object_or_404(User, username=self.kwargs.get('username'))
        context['author'] = author
        context['following'] = (
            self.request.user.is_authenticated
            and author.following.filter(user=self.request.user).exists()
        )
        return context


class PostDetailView(DetailView, FormMixin):
    model = Post
    template_name = 'posts/post_detail.html'
    form_class = CommentForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        post = get_object_or_404(Post, pk=self.object.pk)
        comments = post.comments.all()
        context['comments'] = comments
        return context

    def get_queryset(self):
        return (Post.objects.select_related('author').all()
                .select_related('group').all())


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    form_class = PostForm
    template_name = 'posts/create_post.html'

    def form_valid(self, form):
        new_post = form.save(commit=False)
        new_post.author = self.request.user
        new_post.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy(
            'posts:profile',
            args=(self.request.user.username,)
        )


class PostEditView(LoginRequiredMixin, UpdateView):
    model = Post
    form_class = PostForm
    template_name = 'posts/create_post.html'
    object = None

    def get_context_data(self):
        context = super().get_context_data()
        context['is_edit'] = True
        return context

    def get_queryset(self):
        return (Post.objects.select_related('group').all()
                .select_related('author').all())

    def dispatch(self, request, *args, **kwargs):
        instance = self.get_object()
        if instance.author != self.request.user:
            return redirect(
                reverse_lazy('posts:post_detail', args=(instance.pk,))
            )
        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return reverse_lazy('posts:post_detail', args=(self.object.pk,))


class AddCommentView(LoginRequiredMixin, CreateView):
    model = Comment
    form_class = CommentForm

    def form_valid(self, form):
        post = get_object_or_404(Post, pk=self.kwargs.get('pk'))
        new_comment = form.save(commit=False)
        new_comment.post = post
        new_comment.author = self.request.user
        new_comment.save()
        return redirect(reverse('posts:post_detail', args=(post.pk,)))


class FollowingListView(LoginRequiredMixin, ListView):
    paginate_by = settings.COUNT_OF_POSTS_PAGINATOR
    model = Post
    template_name = 'posts/index.html'

    def get_context_data(self):
        context = super().get_context_data()
        context['following_view'] = True
        context['cache_seconds'] = settings.CACHE_PAGE_SECONDS
        return context

    def get_queryset(self):
        return Post.objects.filter(author__following__user=self.request.user)


class FollowAuthor(LoginRequiredMixin, View):
    model = User
    template_name = 'posts/profile.html'

    def get(self, *args, **kwargs):
        author = get_object_or_404(User, username=self.kwargs.get('username'))
        if author != self.request.user:
            Follow.objects.get_or_create(author=author, user=self.request.user)
        return redirect(reverse(
            'posts:profile',
            args=(self.kwargs.get('username'),)
        ))


class UnFollowAuthor(LoginRequiredMixin, View):
    model = User
    template_name = 'posts/profile.html'

    def get(self, *args, **kwargs):
        author = get_object_or_404(User, username=self.kwargs.get('username'))
        is_follower = Follow.objects.filter(
            user=self.request.user,
            author=author,
        )
        is_follower.delete()
        return redirect(
            reverse('posts:profile', args=(self.kwargs.get('username'),))
        )

yatube/templates/posts/create_post.html
{% extends "base.html" %}
{% block title %}
  {% if is_edit %}
    Редактировать запись
  {% else %}
    Создать пост
  {% endif %}
{% endblock title %}
{% block content %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            {% if is_edit %}
              Редактировать запись
            {% else %}
              Новый пост
            {% endif %}
          </div>
          <div>
            {% if is_edit %}
              {% include "includes/form.html" with button_name="Сохранить" %}
            {% else %}
              {% include "includes/form.html" with button_name="Добавить" %}
            {% endif %}
          </div> 
        </div> 
      </div>
    </div> 
  </div> 
{% endblock content %}

yatube/templates/posts/group_list.html
{% extends "base.html" %}
{% block title %}Сообщества YaTube{% endblock title %}
{% block header %}{{ group.title }}{% endblock %}
{% block content %}
  <div class="container">
    <h1>{{ group.title }}</h1>
    <p>{{ group.description }}</p>
    {% for post in page_obj %}
      {% include "includes/post.html" with is_detail=True %}
    {% endfor %}
    {% include "posts/includes/paginator.html" %}
  </div>
{% endblock content %} 
    

yatube/templates/posts/index.html
{% extends "base.html" %}
{% block title %}
  {% if following_view %}
    Обновления авторов из ваших подписок
  {% else %}
    Последние обновления на сайте
  {% endif %}
{% endblock title %}
{% block content %}
  <div class="container py-5">
    {% include 'posts/includes/switcher.html' %}
    {% load cache %}
    {% cache cache_seconds page_obj.number request %}
      {% for post in page_obj %}
        {% if post.group %}
          {% include "includes/post.html" with link_to_group=post.group.slug is_detail=True %}
        {% else %}
          {% include "includes/post.html" with is_detail=True %}
        {% endif %}
        {% empty %}
          {% if following_view %}
            Пока у вас нет никаких подписок, чтобы тут появились посты - подпишитесь на авторов.
          {% else %}
            Никто еще ничего не запостил на сайт. Будьте первым!
          {% endif %}
      {% endfor %}
    {% endcache %}
    {% include "posts/includes/paginator.html" %}
  </div>
{% endblock content %}
    

yatube/templates/posts/post_detail.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}{{ post.text|slice:":30" }}{% endblock title %}
{% block content %}
  <div class="container py-5">
    <div class="row">
      <aside class="col-12 col-md-3">
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
          {% if post.group %}
            <li class="list-group-item">
              Группа: {{ post.group }}
              <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
            </li>
          {% endif %}
          <li class="list-group-item">
            Автор: {{ post.author.get_full_name }}
          </li>
          <li class="list-group-item d-flex justify-content-between align-items-center">
            Всего постов автора: <span>{{ post.author.posts.count }}</span>
          </li>
          <li class="list-group-item">
            <a href="{% url 'posts:profile' post.author.username %}">все записи пользователя</a>
          </li>
        </ul>
      </aside>
      <article class="col-12 col-md-9">
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <p>
          {{ post.text }}
        </p>
        {% if post.author == user %}
          <a class="btn btn-primary" href="{% url 'posts:post_edit' post.id %}">
            Редактировать запись
          </a>
        {% endif %}
      </article>
    </div>
    {% load user_filters %}
    <hr/>
    {% for comment in comments %}
      <div class="container md-5">
      <div class="media-body">
        <h5 class="mt-0">
          <a href="{% url 'posts:profile' comment.author.username %}">
            {{ comment.author.username }}
          </a>
        </h5>
        <p>
          {{ comment.text }}
        </p>
      </div>
      <hr/>
    {% endfor %}
    {% if user.is_authenticated %}
      <div class="card my-4">
        <h5 class="card-header">Добавить комментарий:</h5>
        <div class="card-body">
          <form method="post" action="{% url 'posts:add_comment' post.id %}">
            {% csrf_token %}
            <div class="form-group mb-2">
              {{ form.text|addclass:"form-control" }}
            </div>
            <button type="submit" class="btn btn-primary">Отправить</button>
          </form>
        </div>
      </div>
    {% endif %}
    </div>
  </div>
{% endblock content %}

yatube/templates/posts/profile.html
{% extends "base.html" %}
{% block title %}{{ author.get_full_name }} профайл
  пользователя{% endblock title %}
{% block content %}
  <div class="container py-5">
      <aside class="col-12 col-md-3">
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            Все посты пользователя <b>{{ author.get_full_name }}</b><br>
          </li>
          <li class="list-group-item">
            Имя пользователя: <b>{{ author.username }}</b>
          </li>
          <li class="list-group-item">
            Всего постов: <b>{{ author.posts.count }}</b>
          </li>
          <li class="list-group-item">
            Подписок на автора: <b>{{ author.following.count }}</b>
          </li>
          <li class="list-group-item">
            Подписан: <b>{{ author.follower.count }}</b>
          </li>
          {% if author != user and user.is_authenticated %}
            <li class="list-group-item">
              {% if following %}
                <a
                  class="btn btn-lg btn-light"
                  href="{% url 'posts:profile_unfollow' author.username %}"
                  role="button"
                >
                  Отписаться
                </a>
              {% else %}
                <a
                  class="btn btn-lg btn-primary"
                  href="{% url 'posts:profile_follow' author.username %}"
                  role="button"
                >
                  Подписаться
                </a>
                </li>
              {% endif %}
            </ul>
          {% endif %}
      </aside>
      {% for post in page_obj %}
        {% if post.group %}
          {% include "includes/post.html" with link_to_group=post.group.slug %}
        {% else %}
          {% include "includes/post.html" %}
        {% endif %}
      {% endfor %}
      {% include "posts/includes/paginator.html" %}
    </div>
{% endblock content %}